import { Router } from 'express';
import { z } from 'zod';

import { mcpCatalogExists, readMcpCatalog } from '../mcp-catalog.js';
import { defineRoute } from '../lib/route-builder.js';
import {
  ApiErrorSchema,
  McpCatalogSchema,
} from '../schemas/index.js';

const router = Router();

defineRoute(router, {
  method: 'get',
  path: '/api/mcp/servers',
  summary: 'MCP server catalog',
  description:
    'Returns the static MCP server catalog generated at API startup: ' +
    'every registered server (always-on `nanoclaw` IPC server plus the ' +
    'opt-in servers under `container/mcp-servers/`) with the tool names ' +
    'each one registers. Use this to discover valid values for ' +
    '`containerConfig.deniedTools`.\n\n' +
    'The catalog is generated by a one-shot FS scan + regex over each ' +
    'server\'s `server.tool(` calls and is NOT regenerated on every ' +
    'request. Restart the API to refresh.',
  responses: {
    200: {
      description: 'MCP catalog',
      schema: z.object({ data: McpCatalogSchema }),
    },
    503: {
      description: 'Catalog not generated at startup',
      schema: ApiErrorSchema,
    },
  },
  handler: (_req, res) => {
    if (!mcpCatalogExists()) {
      res.status(503).json({
        error:
          'MCP catalog not generated. Restart the API server to regenerate mcp-catalog.json.',
        code: 'NOT_CONFIGURED',
      });
      return;
    }
    res.json({ data: readMcpCatalog() });
  },
});

export default router;
